# Site settings
title:       Krishan Subudhi Blog
email:       krishan.subudhi@gmail.com
author:      Krishan Subudhi
description: "Simple tech blog by Krishan Subudhi"
baseurl:     ""
url:         "http://krishansubudhi.github.io"

# Google analytics
google_analytics:

# Optional features
animated:           true
show_related_posts: true
show_post_footers:  false
show_social_icons:  true

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
github_username:krishansubudhi
stackoverflow_id:
twitter_username:krishanrockz
google_plus_id:+krishansubudhi
linkedin_username:104802110
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: true
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: true
share_linkedin: true
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     4
sass:
  compressed: true
gems:
  - jekyll-sitemap
